### PR TITLE
Project scaffolded

### PR DESCRIPTION
**Pull request by yaqwaqwa**

### CODE REVIEW

**Review by MaddieLymei — COMMENTED** [review]
Looks good! What is BudgetComponent's use in each of the files?

**Comment by ToriBench** [comment]
Cool stuff! Can you just take out the name "component" from all the budget layers? Just to stick to a consistent naming standard :)

**Review by ToriBench — CHANGES_REQUESTED** [review]
Please change the names of the different budget layers. Remove "Component".

**Review by PauloN1 — APPROVED** [review]

**Comment by tshiamomahloko** [comment]
Way too old

**Pull request closed without merging**
